# Generated by Django 4.1.5 on 2023-01-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="수정일시"),
                ),
                ("name", models.CharField(max_length=20)),
                ("student_id", models.CharField(max_length=20)),
                ("mobile", models.CharField(max_length=20, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("birth", models.DateField(null=True)),
                ("major", models.CharField(max_length=40, null=True)),
                ("grade", models.IntegerField(null=True, verbose_name="학년")),
                ("join_year", models.IntegerField(null=True, verbose_name="기수")),
                ("study_class", models.IntegerField(null=True, verbose_name="반")),
                ("role", models.CharField(max_length=20, null=True)),
                ("status", models.CharField(max_length=20, null=True)),
                ("boj_handle", models.CharField(max_length=20, null=True)),
            ],
            options={"verbose_name": "Contact", "verbose_name_plural": "Contact",},
        ),
    ]
