# Generated by Django 4.1.5 on 2023-01-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0002_alter_contact_join_year_alter_contact_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact", name="memo", field=models.TextField(null=True),
        ),
    ]
