# Generated by Django 4.1.5 on 2023-01-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0003_contact_memo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="grade",
            field=models.CharField(max_length=10, null=True, verbose_name="학년"),
        ),
    ]
