# Generated by Django 4.1.5 on 2023-01-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0004_alter_contact_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="birth",
            field=models.DateField(null=True, verbose_name="생년월일"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="boj_handle",
            field=models.CharField(max_length=20, null=True, verbose_name="BOJ 핸들"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254, null=True, verbose_name="이메일"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="major",
            field=models.CharField(max_length=40, null=True, verbose_name="소속"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="memo",
            field=models.TextField(null=True, verbose_name="비고"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="mobile",
            field=models.CharField(max_length=20, null=True, verbose_name="연락처"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=20, verbose_name="이름"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="role",
            field=models.CharField(max_length=20, null=True, verbose_name="직급"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="status",
            field=models.CharField(max_length=20, null=True, verbose_name="회원 구분"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="student_id",
            field=models.CharField(db_index=True, max_length=20, verbose_name="학번"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="study_class",
            field=models.CharField(max_length=20, null=True, verbose_name="분반"),
        ),
    ]
